### ISSUE TITLE
expect reduceSansAcc should equal 30, not 28

### ISSUE THREAD

**Issue by edwinlin** [learn-co-curriculum/js-functional-library-project#16]
describe('reduce', function () {
    const testArr = unmodifiedTestArr.slice() // arr is [1, 2, 3, 4]
    const callback = (acc, val, collection) => (acc + (val * 3))
    const reduceSansAcc = fi.reduce(testArr, callback)
    const reduceWithAcc = fi.reduce(testArr, callback, 10)

    it('returns the correct reduced value when passed an accumulator', function () {
      expect(reduceWithAcc).to.equal(40)
    })

    it('returns the correct reduced value when not passed an accumulator', function () {
      expect(reduceSansAcc).to.equal(30)
    })

    it('does not modify the original array', function () {
      expect(arraysEqual(unmodifiedTestArr, testArr)).to.equal(true)
    })

  })

**Comment by sgharms** [comment]
@edwinlin 

I think you might not _quite_ be fully understanding the way this code is
working. Try discussing your issue via the [Ask a Question][AAQ] tool. You're
close, so stick with it!

As a hint, look at what Chrome thinks the answer is:

![image](https://user-images.githubusercontent.com/50019/53905338-4f92f500-4016-11e9-8716-8af982263983.png)

The MDN documentation provides the crucial piece of information!

[AAQ]: http://help.learn.co/ask-a-question/where-can-i-ask-a-question-about-a-lesson
